# Generated by Django 4.2.5 on 2023-09-25 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'labels',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='email title')),
                ('text', models.TextField(blank=True, null=True, verbose_name='email text')),
                ('file', models.FileField(blank=True, null=True, upload_to='attached_files')),
                ('draft', models.BooleanField(default=False)),
                ('bcc_receivers', models.ManyToManyField(related_name='bcc_receivers', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='email_categories', to='email_module.category')),
                ('cc_receivers', models.ManyToManyField(related_name='cc_receivers', to=settings.AUTH_USER_MODEL)),
                ('direct_receivers', models.ManyToManyField(related_name='direct_receivers', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(related_name='email_labels', to='email_module.label', verbose_name='email_labels')),
                ('sender', models.ForeignKey(on_delete=models.SET('deleted_account'), related_name='sent_Emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'emails',
            },
        ),
    ]
