# Generated by Django 5.0.2 on 2024-03-13 11:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='email body'),
        ),
    ]
