# Generated by Django 4.2.5 on 2023-10-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='bcc_receivers',
        ),
        migrations.RemoveField(
            model_name='email',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='email',
            name='cc_receivers',
        ),
        migrations.RemoveField(
            model_name='email',
            name='direct_receivers',
        ),
        migrations.RemoveField(
            model_name='email',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='label',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
