# Generated by Django 5.0.2 on 2024-03-14 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_module', '0002_alter_email_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='archived_by_user',
            field=models.ManyToManyField(related_name='archived_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='bcc_receivers',
            field=models.ManyToManyField(related_name='bcc_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc_receivers',
            field=models.ManyToManyField(related_name='cc_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='deleted_by_user',
            field=models.ManyToManyField(related_name='deleted_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='direct_receivers',
            field=models.ManyToManyField(related_name='direct_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='labels',
            field=models.ManyToManyField(related_name='emails_with_this_label', to='email_module.label', verbose_name='email_labels'),
        ),
        migrations.AlterField(
            model_name='email',
            name='read_by_user',
            field=models.ManyToManyField(related_name='read_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
