# Generated by Django 4.2.5 on 2023-10-20 21:09

from django.db import migrations, models
import django.db.models.deletion
import email_module.validators


class Migration(migrations.Migration):

    dependencies = [
        ('email_module', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='email_module.email'),
        ),
        migrations.AlterField(
            model_name='email',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attached_files', validators=[email_module.validators.validate_file_size]),
        ),
    ]
