# Generated by Django 5.0.2 on 2024-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_module', '0004_alter_email_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
