# Generated by Django 4.2.5 on 2023-11-19 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_module', '0004_email_reply_alter_email_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc_receivers',
            field=models.ManyToManyField(blank=True, related_name='bcc_receivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='email_categories', to='email_module.category'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc_receivers',
            field=models.ManyToManyField(blank=True, related_name='cc_receivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='direct_receivers',
            field=models.ManyToManyField(blank=True, related_name='direct_receivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='email',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='email_labels', to='email_module.label', verbose_name='email_labels'),
        ),
    ]
