# Generated by Django 4.2.5 on 2023-11-19 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_module', '0005_alter_email_bcc_receivers_alter_email_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='email_module.email'),
        ),
    ]
