# Generated by Django 5.0.2 on 2024-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_module', '0005_alter_label_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(max_length=50),
        ),
    ]
