# Generated by Django 4.2.5 on 2023-11-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_module', '0007_remove_email_reply_email_replied_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
