# Generated by Django 4.2.5 on 2024-02-06 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_background_color', models.CharField(blank=True, choices=[('#ffffcc', 'light lime'), ('#ddccff', 'light purple'), ('#cce0ff', 'light ocean blue'), ('#ccf5ff', 'light sky blue'), ('#ffcccc', 'light red'), ('white', 'white'), ('#f3ccff', 'pink purple')], default='#f3ccff', max_length=7)),
                ('sidebar_background_color', models.CharField(blank=True, choices=[('#ffffcc', 'light lime'), ('#ddccff', 'light purple'), ('#cce0ff', 'light ocean blue'), ('#ccf5ff', 'light sky blue'), ('#ffcccc', 'light red'), ('white', 'white'), ('#f3ccff', 'pink purple')], default='white', max_length=7)),
                ('main_background_color', models.CharField(blank=True, choices=[('#ffffcc', 'light lime'), ('#ddccff', 'light purple'), ('#cce0ff', 'light ocean blue'), ('#ccf5ff', 'light sky blue'), ('#ffcccc', 'light red'), ('white', 'white'), ('#f3ccff', 'pink purple')], default='white', max_length=7)),
                ('icons_color', models.CharField(blank=True, choices=[('c', 'colored'), ('bw', 'black and white')], default='c', max_length=2)),
                ('background_image', models.CharField(blank=True, choices=[('images/background_pictures/bg_no1.jpg', 'background 1'), ('images/background_pictures/bg_no2.jpg', 'background 2'), ('images/background_pictures/bg_no3.jpg', 'background 3'), ('images/background_pictures/bg_no4.jpg', 'background 4'), ('images/background_pictures/bg_no5.jpg', 'background 5'), ('images/background_pictures/bg_no6.jpg', 'background 6'), ('images/background_pictures/bg_no7.jpg', 'background 7')], default=None, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
