# Generated by Django 5.0.2 on 2024-03-13 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=7, unique=True)),
                ('color_image', models.ImageField(db_index=True, unique=True, upload_to='background_colors_images', verbose_name='Background Color Images')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='background_images', verbose_name='background image')),
            ],
            options={
                'verbose_name': 'Predefined Background Image',
                'verbose_name_plural': 'Predefined Background Images',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons_color', models.CharField(choices=[('c', 'colored'), ('bw', 'black and white')], default='c', max_length=2)),
                ('background_image', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_module.backgroundimage')),
                ('header_background_color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_background_color_settings', to='site_module.backgroundcolor')),
                ('main_background_color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_background_color_settings', to='site_module.backgroundcolor')),
                ('sidebar_background_color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sidebar_background_color_settings', to='site_module.backgroundcolor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siteSettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
