# Generated by Django 5.0.2 on 2024-02-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_alter_sitesettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_image',
            field=models.CharField(blank=True, choices=[('/static/images/background_pictures/bg_no1.jpg', 'background 1'), ('/static/images/background_pictures/bg_no2.jpg', 'background 2'), ('/static/images/background_pictures/bg_no3.jpg', 'background 3'), ('/static/images/background_pictures/bg_no4.jpg', 'background 4'), ('/static/images/background_pictures/bg_no5.jpg', 'background 5'), ('/static/images/background_pictures/bg_no6.jpg', 'background 6'), ('/static/images/background_pictures/bg_no7.jpg', 'background 7')], default=None, max_length=48, null=True),
        ),
    ]
