# Generated by Django 5.0.2 on 2024-02-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0006_alter_sitesettings_header_background_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=7)),
                ('color_image', models.ImageField(upload_to='background_colors_images', verbose_name='Background Color Images')),
            ],
        ),
    ]
