# Generated by Django 5.0.2 on 2024-02-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_backgroundcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=12)),
                ('image', models.ImageField(upload_to='background_images', verbose_name='background image')),
            ],
            options={
                'verbose_name': 'Predefined Background Image',
                'verbose_name_plural': 'Predefined Background Images',
            },
        ),
    ]
