# Generated by Django 5.0.2 on 2024-02-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundcolor',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_colors_images', verbose_name='Background Color Images'),
        ),
    ]
