# Generated by Django 5.0.2 on 2024-02-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_alter_backgroundcolor_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundcolor',
            name='color_image',
            field=models.ImageField(upload_to='background_colors_images', verbose_name='Background Color Images'),
        ),
    ]
