# Generated by Django 5.0.2 on 2024-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0010_alter_backgroundcolor_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundcolor',
            name='color_image',
            field=models.ImageField(unique=True, upload_to='background_colors_images', verbose_name='Background Color Images'),
        ),
        migrations.AlterField(
            model_name='backgroundcolor',
            name='color_name',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(unique=True, upload_to='background_images', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image_name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
