# Generated by Django 5.0.2 on 2024-02-25 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0011_alter_backgroundcolor_color_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_module.backgroundimage'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_background_color',
            field=models.ForeignKey(default='#f3ccff', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='header_background_color_settings', to='site_module.backgroundcolor'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='main_background_color',
            field=models.ForeignKey(default='white', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_background_color_settings', to='site_module.backgroundcolor'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='sidebar_background_color',
            field=models.ForeignKey(default='white', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sidebar_background_color_settings', to='site_module.backgroundcolor'),
        ),
    ]
