# Generated by Django 5.0.2 on 2024-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0014_alter_sitesettings_header_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='icons_color',
            field=models.CharField(choices=[('c', 'colored'), ('bw', 'black and white')], default='c', max_length=2),
        ),
    ]
