# Generated by Django 5.0.2 on 2024-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0015_alter_sitesettings_icons_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundcolor',
            name='color_image',
            field=models.ImageField(db_index=True, unique=True, upload_to='background_colors_images', verbose_name='Background Color Images'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(db_index=True, unique=True, upload_to='background_images', verbose_name='background image'),
        ),
    ]
