# Generated by Django 5.0.2 on 2024-03-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0016_alter_backgroundcolor_color_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='background_images', verbose_name='background image'),
        ),
    ]
