# Generated by Django 5.0.2 on 2024-03-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0017_alter_backgroundimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
