# Generated by Django 4.2.5 on 2023-10-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
