# Generated by Django 4.2.5 on 2023-10-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0008_otpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.DeleteModel(
            name='OtpCode',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
