# Generated by Django 4.2.5 on 2023-10-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0011_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpCode',
        ),
    ]
