# Generated by Django 4.2.5 on 2023-10-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0012_delete_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_column='recovery_email', db_index=True, max_length=300, null=True, unique=True, verbose_name='recovery email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
