# Generated by Django 4.2.5 on 2023-10-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0015_alter_otpcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
