# Generated by Django 4.2.5 on 2023-11-14 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0017_passwordhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_passwords', to=settings.AUTH_USER_MODEL),
        ),
    ]
